name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript Build
        run: npm run build
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

  deploy-staging:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref_name == 'main'

    steps:
      - name: Deploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: "${{ secrets.STAGIN_DEPLOY_KEY }}"
